# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windows(object):
    def setupUi(self, windows):
        windows.setObjectName("windows")
        windows.resize(851, 555)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/image/icons8-inspection-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        windows.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(windows)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_4.addWidget(self.tableWidget)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnPDF = QtWidgets.QPushButton(self.centralwidget)
        self.btnPDF.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/image/icons8-pdf-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPDF.setIcon(icon1)
        self.btnPDF.setIconSize(QtCore.QSize(40, 40))
        self.btnPDF.setObjectName("btnPDF")
        self.verticalLayout_3.addWidget(self.btnPDF)
        self.btnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.btnEdit.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/image/icons8-save-as-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEdit.setIcon(icon2)
        self.btnEdit.setIconSize(QtCore.QSize(40, 40))
        self.btnEdit.setObjectName("btnEdit")
        self.verticalLayout_3.addWidget(self.btnEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.btnClean = QtWidgets.QPushButton(self.centralwidget)
        self.btnClean.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/image/icons8-delete-bin-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClean.setIcon(icon3)
        self.btnClean.setIconSize(QtCore.QSize(40, 40))
        self.btnClean.setObjectName("btnClean")
        self.verticalLayout_3.addWidget(self.btnClean)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout_8.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        self.formLayout_3.setObjectName("formLayout_3")
        self.primerPlatoLabel = QtWidgets.QLabel(self.groupBox)
        self.primerPlatoLabel.setObjectName("primerPlatoLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.primerPlatoLabel)
        self.primerPlatoLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.primerPlatoLineEdit.setClearButtonEnabled(True)
        self.primerPlatoLineEdit.setObjectName("primerPlatoLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.primerPlatoLineEdit)
        self.segundoPlatoLabel = QtWidgets.QLabel(self.groupBox)
        self.segundoPlatoLabel.setObjectName("segundoPlatoLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.segundoPlatoLabel)
        self.segundoPlatoLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.segundoPlatoLineEdit.setClearButtonEnabled(True)
        self.segundoPlatoLineEdit.setObjectName("segundoPlatoLineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.segundoPlatoLineEdit)
        self.gridLayout.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        self.formLayout_4.setObjectName("formLayout_4")
        self.primerPlatoLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.primerPlatoLabel_2.setObjectName("primerPlatoLabel_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.primerPlatoLabel_2)
        self.primerPlatoLineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.primerPlatoLineEdit_2.setClearButtonEnabled(True)
        self.primerPlatoLineEdit_2.setObjectName("primerPlatoLineEdit_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.primerPlatoLineEdit_2)
        self.segundoPlatoLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.segundoPlatoLabel_2.setObjectName("segundoPlatoLabel_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.segundoPlatoLabel_2)
        self.segundoPlatoLineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.segundoPlatoLineEdit_2.setClearButtonEnabled(True)
        self.segundoPlatoLineEdit_2.setObjectName("segundoPlatoLineEdit_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.segundoPlatoLineEdit_2)
        self.gridLayout_2.addLayout(self.formLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        self.formLayout_5.setObjectName("formLayout_5")
        self.primerPlatoLabel_3 = QtWidgets.QLabel(self.groupBox_3)
        self.primerPlatoLabel_3.setObjectName("primerPlatoLabel_3")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.primerPlatoLabel_3)
        self.primerPlatoLineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.primerPlatoLineEdit_3.setClearButtonEnabled(True)
        self.primerPlatoLineEdit_3.setObjectName("primerPlatoLineEdit_3")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.primerPlatoLineEdit_3)
        self.segundoPlatoLabel_3 = QtWidgets.QLabel(self.groupBox_3)
        self.segundoPlatoLabel_3.setObjectName("segundoPlatoLabel_3")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.segundoPlatoLabel_3)
        self.segundoPlatoLineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.segundoPlatoLineEdit_3.setClearButtonEnabled(True)
        self.segundoPlatoLineEdit_3.setObjectName("segundoPlatoLineEdit_3")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.segundoPlatoLineEdit_3)
        self.gridLayout_3.addLayout(self.formLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setCheckable(True)
        self.groupBox_4.setChecked(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        self.formLayout_6.setObjectName("formLayout_6")
        self.primerPlatoLabel_4 = QtWidgets.QLabel(self.groupBox_4)
        self.primerPlatoLabel_4.setObjectName("primerPlatoLabel_4")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.primerPlatoLabel_4)
        self.primerPlatoLineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.primerPlatoLineEdit_4.setClearButtonEnabled(True)
        self.primerPlatoLineEdit_4.setObjectName("primerPlatoLineEdit_4")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.primerPlatoLineEdit_4)
        self.segundoPlatoLabel_4 = QtWidgets.QLabel(self.groupBox_4)
        self.segundoPlatoLabel_4.setObjectName("segundoPlatoLabel_4")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.segundoPlatoLabel_4)
        self.segundoPlatoLineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.segundoPlatoLineEdit_4.setClearButtonEnabled(True)
        self.segundoPlatoLineEdit_4.setObjectName("segundoPlatoLineEdit_4")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.segundoPlatoLineEdit_4)
        self.gridLayout_4.addLayout(self.formLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setCheckable(True)
        self.groupBox_5.setChecked(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        self.formLayout_7.setObjectName("formLayout_7")
        self.primerPlatoLabel_5 = QtWidgets.QLabel(self.groupBox_5)
        self.primerPlatoLabel_5.setObjectName("primerPlatoLabel_5")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.primerPlatoLabel_5)
        self.primerPlatoLineEdit_5 = QtWidgets.QLineEdit(self.groupBox_5)
        self.primerPlatoLineEdit_5.setClearButtonEnabled(True)
        self.primerPlatoLineEdit_5.setObjectName("primerPlatoLineEdit_5")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.primerPlatoLineEdit_5)
        self.segundoPlatoLabel_5 = QtWidgets.QLabel(self.groupBox_5)
        self.segundoPlatoLabel_5.setObjectName("segundoPlatoLabel_5")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.segundoPlatoLabel_5)
        self.segundoPlatoLineEdit_5 = QtWidgets.QLineEdit(self.groupBox_5)
        self.segundoPlatoLineEdit_5.setClearButtonEnabled(True)
        self.segundoPlatoLineEdit_5.setObjectName("segundoPlatoLineEdit_5")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.segundoPlatoLineEdit_5)
        self.gridLayout_5.addLayout(self.formLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_5)
        spacerItem6 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.imgLogo = QtWidgets.QLabel(self.tab_2)
        self.imgLogo.setMinimumSize(QtCore.QSize(150, 150))
        self.imgLogo.setMaximumSize(QtCore.QSize(150, 150))
        self.imgLogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imgLogo.setText("")
        self.imgLogo.setPixmap(QtGui.QPixmap(":/images/image/icons8-orange-juice-100.png"))
        self.imgLogo.setScaledContents(True)
        self.imgLogo.setObjectName("imgLogo")
        self.verticalLayout.addWidget(self.imgLogo)
        self.btnADDLOGO = QtWidgets.QPushButton(self.tab_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/image/icons8-add-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnADDLOGO.setIcon(icon4)
        self.btnADDLOGO.setIconSize(QtCore.QSize(25, 25))
        self.btnADDLOGO.setObjectName("btnADDLOGO")
        self.verticalLayout.addWidget(self.btnADDLOGO)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        self.formLayout.setObjectName("formLayout")
        self.nombreLabel = QtWidgets.QLabel(self.tab_2)
        self.nombreLabel.setObjectName("nombreLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nombreLabel)
        self.nombreLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.nombreLineEdit.setClearButtonEnabled(True)
        self.nombreLineEdit.setObjectName("nombreLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nombreLineEdit)
        self.descripciNLabel = QtWidgets.QLabel(self.tab_2)
        self.descripciNLabel.setObjectName("descripciNLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.descripciNLabel)
        self.descripciNLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.descripciNLineEdit.setClearButtonEnabled(True)
        self.descripciNLineEdit.setObjectName("descripciNLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.descripciNLineEdit)
        self.pedidoHastaLabel = QtWidgets.QLabel(self.tab_2)
        self.pedidoHastaLabel.setObjectName("pedidoHastaLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pedidoHastaLabel)
        self.pedidoHastaTimeEdit = QtWidgets.QTimeEdit(self.tab_2)
        self.pedidoHastaTimeEdit.setCalendarPopup(False)
        self.pedidoHastaTimeEdit.setTime(QtCore.QTime(10, 0, 0))
        self.pedidoHastaTimeEdit.setObjectName("pedidoHastaTimeEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pedidoHastaTimeEdit)
        self.envioGratisLabel = QtWidgets.QLabel(self.tab_2)
        self.envioGratisLabel.setObjectName("envioGratisLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.envioGratisLabel)
        self.envioGratisCheckBox = QtWidgets.QCheckBox(self.tab_2)
        self.envioGratisCheckBox.setText("")
        self.envioGratisCheckBox.setChecked(True)
        self.envioGratisCheckBox.setObjectName("envioGratisCheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.envioGratisCheckBox)
        self.horizontalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        self.formLayout_2.setObjectName("formLayout_2")
        self.facebookLabel = QtWidgets.QLabel(self.tab_2)
        self.facebookLabel.setObjectName("facebookLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.facebookLabel)
        self.facebookLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.facebookLineEdit.setClearButtonEnabled(True)
        self.facebookLineEdit.setObjectName("facebookLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.facebookLineEdit)
        self.instagramLabel = QtWidgets.QLabel(self.tab_2)
        self.instagramLabel.setObjectName("instagramLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.instagramLabel)
        self.instagramLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.instagramLineEdit.setClearButtonEnabled(True)
        self.instagramLineEdit.setObjectName("instagramLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.instagramLineEdit)
        self.twitterLabel = QtWidgets.QLabel(self.tab_2)
        self.twitterLabel.setObjectName("twitterLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.twitterLabel)
        self.twitterLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.twitterLineEdit.setClearButtonEnabled(True)
        self.twitterLineEdit.setObjectName("twitterLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.twitterLineEdit)
        self.whatsappLabel = QtWidgets.QLabel(self.tab_2)
        self.whatsappLabel.setObjectName("whatsappLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.whatsappLabel)
        self.whatsappLineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.whatsappLineEdit.setClearButtonEnabled(True)
        self.whatsappLineEdit.setObjectName("whatsappLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.whatsappLineEdit)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.gridLayout_7.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_4.addItem(spacerItem10)
        self.btnDB = QtWidgets.QPushButton(self.centralwidget)
        self.btnDB.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/image/icons8-data-recovery-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDB.setIcon(icon5)
        self.btnDB.setIconSize(QtCore.QSize(70, 70))
        self.btnDB.setObjectName("btnDB")
        self.verticalLayout_4.addWidget(self.btnDB)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setMinimumSize(QtCore.QSize(91, 50))
        self.btnSave.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/image/icons8-save-close-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon6)
        self.btnSave.setIconSize(QtCore.QSize(70, 70))
        self.btnSave.setObjectName("btnSave")
        self.verticalLayout_4.addWidget(self.btnSave)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.gridLayout_8.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblLogo = QtWidgets.QLabel(self.centralwidget)
        self.lblLogo.setMaximumSize(QtCore.QSize(50, 50))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap(":/images/image/icons8-inspection-100.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setObjectName("lblLogo")
        self.horizontalLayout_6.addWidget(self.lblLogo)
        self.lblTitle = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Swis721 BdCnOul BT")
        font.setPointSize(24)
        font.setItalic(False)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.horizontalLayout_6.addWidget(self.lblTitle)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.btnClose = QtWidgets.QPushButton(self.centralwidget)
        self.btnClose.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/image/icons8-close-window-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon7)
        self.btnClose.setIconSize(QtCore.QSize(30, 30))
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_6.addWidget(self.btnClose)
        self.gridLayout_8.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_8.addItem(spacerItem13, 1, 0, 1, 1)
        windows.setCentralWidget(self.centralwidget)

        self.retranslateUi(windows)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(windows)

    def retranslateUi(self, windows):
        _translate = QtCore.QCoreApplication.translate
        windows.setWindowTitle(_translate("windows", "QMenú"))
        self.btnPDF.setToolTip(_translate("windows", "Guardar en PDF"))
        self.btnEdit.setToolTip(_translate("windows", "Editar Menú"))
        self.btnClean.setToolTip(_translate("windows", "Eliminar Menú"))
        self.groupBox.setTitle(_translate("windows", "Lunes"))
        self.primerPlatoLabel.setText(_translate("windows", "Plato Común"))
        self.segundoPlatoLabel.setText(_translate("windows", "Plato Light"))
        self.groupBox_2.setTitle(_translate("windows", "Martes"))
        self.primerPlatoLabel_2.setText(_translate("windows", "Plato Común"))
        self.segundoPlatoLabel_2.setText(_translate("windows", "Plato Light"))
        self.groupBox_3.setTitle(_translate("windows", "Miércoles"))
        self.primerPlatoLabel_3.setText(_translate("windows", "Plato Común"))
        self.segundoPlatoLabel_3.setText(_translate("windows", "Plato Light"))
        self.groupBox_4.setTitle(_translate("windows", "Jueves"))
        self.primerPlatoLabel_4.setText(_translate("windows", "Plato Común"))
        self.segundoPlatoLabel_4.setText(_translate("windows", "Plato Light"))
        self.groupBox_5.setTitle(_translate("windows", "Viernes"))
        self.primerPlatoLabel_5.setText(_translate("windows", "Plato Común"))
        self.segundoPlatoLabel_5.setText(_translate("windows", "Plato Light"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("windows", "Menú"))
        self.btnADDLOGO.setText(_translate("windows", "Seleccionar"))
        self.nombreLabel.setText(_translate("windows", "Nombre"))
        self.descripciNLabel.setText(_translate("windows", "Descripción"))
        self.pedidoHastaLabel.setText(_translate("windows", "Pedido hasta"))
        self.envioGratisLabel.setText(_translate("windows", "Envio Gratis"))
        self.facebookLabel.setText(_translate("windows", "Facebook"))
        self.facebookLineEdit.setPlaceholderText(_translate("windows", "@facebook"))
        self.instagramLabel.setText(_translate("windows", "Instagram"))
        self.instagramLineEdit.setPlaceholderText(_translate("windows", "@instagram"))
        self.twitterLabel.setText(_translate("windows", "Twitter"))
        self.twitterLineEdit.setPlaceholderText(_translate("windows", "@twitter"))
        self.whatsappLabel.setText(_translate("windows", "Whatsapp"))
        self.whatsappLineEdit.setInputMask(_translate("windows", "000-0000000 / 000-0000000"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("windows", "General"))
        self.btnDB.setToolTip(_translate("windows", "Guardar Menú"))
        self.btnSave.setToolTip(_translate("windows", "Guardar General"))
        self.lblTitle.setText(_translate("windows", "QMenú 0.1"))
        self.btnClose.setToolTip(_translate("windows", "Cerrar "))
import views.images_rc
